### PR TITLE
fix: md-data-table injection on md-data-table-tr

### LINKED ISSUE #133: No provider for MdDataTable!
After upgrading to 0.3.3 I now get the following error on load.

```
angular2.dev.js:23730 EXCEPTION: Error: Uncaught (in promise): No provider for MdDataTable! (MdDataTableTr -> MdDataTable)
```

package.json
```json
"dependencies": {
    "angular2": "2.0.0-beta.12",
    "systemjs": "0.19.24",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.35.0",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.2",
    "zone.js": "0.6.6",
    "ng2-material": "^0.3.3"
  },
  "devDependencies": {
    "concurrently": "^2.0.0",
    "jasmine-core": "2.4.1",
    "lite-server": "^2.1.0",
    "typescript": "^1.8.9",
    "typings": "^0.7.9"
  }
```

### PR DESCRIPTION
**Pull request by Gregcop1**
Should fix #133 and #134

### CODE REVIEW

File: ng2-material/components/data_table/data_table_tr.ts [hunk 1]
```diff
@@ -64,15 +64,17 @@ export class MdDataTableTr implements AfterContentInit {
   }
 
   ngAfterContentInit() {
-    let element = this._element.nativeElement;
-    this.isInHeader = element.parentElement.localName === 'thead';
-    this._initListeners();
+    if (null !== this.table && undefined !== this.table) {
```
Comment (justindujardin) [inline ng2-material/components/data_table/data_table_tr.ts]: You should import and use the isPresent helper that angular2 exports instead of two explicit checks.

```
if (isPresent(this.table)) {
  ...
}
```

**Comment by justindujardin** [comment]
I think this will fix the issue, but I wonder if it would be a better fix to NOT include the MdDataTableTr class in the MATERIAL_DIRECTIVES array, and rather make it an explicit directive on the MdDataTable component.  In this way, the very general `tr` selector will only be applied when it's wrapped in a `<md-data-table>` container, instead of to every tr that the MATERIAL_DIRECTIVES are available in.

**Comment by Gregcop1** [comment]
I totally agree. The first version of the component was in this way but I've encountered errors in the example app, so I thought it was probably a bad way of doing this. I can dig more, maybe this noon.

This fix was temporary, to save time of the two people blocked by this bug, but I think, we have to find a way to process MdDataTableTr only on MdDataTable children.

**Comment by ollwenjones** [comment]
@Gregcop1, @justindujardin  I think a cleaner way to handle the `tr` directive issue is just not to use the a `tr` tag selector at all. It's just too general and creates too many opportunities for name-space conflicts. @justindujardin has already established the convention in this repo of using `<tag attribute-selector...` such as the button selector.

My recommendation:  `md-data-row` attribute selector for this directive.
```javascript
selector: '[md-data-row]',
```

Using attribute selectors for the `tr` also opens the possibility of using separate directive for the `thead tr`, and the `tbody tr`s - since they really have different responsibilities 90% of the time. It would simplify the internals, eliminating the logic used to tell which it is from within the single directive, and also make them independently testable.

**Comment by Gregcop1** [comment]
@ollwenjones Nice. I think, it should be a combination of the both solutions.
we may have a selector about `md-data-table-row` and maybe `md-data-table-header-row` but those components shouldn't be usable out of a `md-data-table` component.

**Comment by justindujardin** [comment]
Let's follow up on this and come up with the ideal solution.  In the meantime I'll merge this.
